### ISSUE TITLE
Summary of discussion today

### ISSUE THREAD

**Issue by daniel-wtd** [while-true-do/ansible-role-kvm#1]
Just a note, so that nothing is forgotten :)

- a reboot seems not to be mandatory, but you can find a reboot/wait in ansible-role-system-update
- comments should be removed (except the first line) from *.yml files
- .git_keep (or similar) should be removed
- the role was initialized with the wrong role name

- selinux:
  - selinux related packages are present in ansible-role-selinux, which should be a dependency, if selinux is used on the system
   - just a note for the se-context
   ```
   semanage fcontext -a -t virt_image_t "/vm(/.*)?"; restorecon -R /vm 
   ```
   - selinux related tasks should be put into a seperate selinux.yml and only included, if selinux is wanted

- network:
  - allow paket forwarding
    ```
    sed -i 's/^\(net.ipv4.ip_forward =\).*/\1 1/' /etc/sysctl.conf; sysctl -p
    ```
   the even better solution would be to have this done in a separate file in /etc/sysctl.d/

- tuned:
  - having tuned as an optional dependency is worth to be discussed. it offers a nice profile for virtual-hosts

Nevertheless, very nice approach and a ton of stuff is already done right :+1:

**Comment by Cinux90** [comment]
Thanks for the nice summary. :+1: 
I hope a can offer a new version middle of the week :)

**Comment by Cinux90** [comment]
ok, enhance the role as described below. 
So feel free to review :)

**Comment by daniel-wtd** [comment]
cool, cool. Will have a look asap :)

**Comment by daniel-wtd** [comment]
Review Summary:

- some useless comments in defaults/main.yml
- useful comments in defaults/main.yml missing
- a switchable state like wtd_kvm_ipv4forward: "1" should be wtd_kvm_ipv4forward_state: "1"
- same for wtd_kvm_ipv4forwardfile: "50-ipv4forward.conf" which should be wtd_kvm_ipv4forward_conf: "50-ipv4forward.conf" or wtd_kvm_ipv4forward_file: "50-ipv4forward.conf"
- files directory can be removed via `git -rm`
- useless comments in meta/main.yml should be removed
- a confitional (when selinux wanted/enabled) dependency in meta/main.yml for selinux would be better
- in tasks/main.yml the install task is not only to install, you can have a look at while-true-do.monit for a good example
- in tasks/main.yml it should be "Include SELinux Tasks" (multiple tasks)
- .gitkepp/.git_keep files should be removed, they are only needed for the skeleton to keep the layout present
- the last part of the readme is missing some updates from skeleton

nevertheless:
- technically the role works
- it is a very nice first approach and stable
- the above seems a lot, but this is minor stuff, which is more "cosmetical" and not "functional"

**Comment by Cinux90** [comment]
For Travis failure i open: https://github.com/willthames/ansible-lint/issues/331

**Comment by daniel-wtd** [comment]
was fixed and rebuild triggered. no green :)

**Comment by Cinux90** [comment]
thx @daniel-wtd, so we should be done here. Maybe you can look one last time if there's anything missing? ^^'

**Comment by daniel-wtd** [comment]
Looks cool :)

Will restrict the repo now and close this ticket.
